### PR TITLE
Hardcode the image into tor-exit-notice.html

### PR DESCRIPTION
**Pull request by boldsuck**
Hello, if you have a look at Github again. ;-)
I merged the commits¹ from the torproject.
¹Hardcode the image into tor-exit-notice.html & change http URL's to https.

### CODE REVIEW

**Comment by chgans** [comment]
Hi thanks for the fix.
Any chance you can add a commit that remove "images/how_tor_works_thumb.png" as it's not needed any more.

**Comment by boldsuck** [comment]
OK, done.
Wanted to leave the picture as a reference in case someone has an httpd.

**Comment by chgans** [comment]
Thanks for your contribution!

**Comment by boldsuck** [comment]
I have to thank you for collecting these translations. ;-)

**Pull request merged**
